[workspace]
members = [ ".","common/assetscrawler", "common/texturedisplay" ]
exclude = [ "tools/*", "test/*" ]


[workspace.dependencies]
anyhow = "1.0.102"
image = "0.25.10"
serde = "1.0.228"
serde_json = "1.0.150"
csv = "1.4.0"
toml = "1.1.2"
rand = "0.10.1"

[workspace.package]
version = "0.1.1"
edition = "2024"
license = "MIT"
authors = [ "dlycn" ]


[package]
name = "toolkitengine"

version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
bevy_basisu_loader = "0.6.0"
anyhow = { workspace = true }
image = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
serde_json = { workspace = true }
csv = { workspace = true }
rand = { workspace = true }
bevy-inspector-egui = "0.37.0"
bevy_egui = "0.40.1"


[dependencies.bevy]
version = "0.19.0"
features = ["default","ktx2","dds"]


[dependencies.clap]
version = "4.6.1"
features = [ "derive", "color" ]



[profile.dev]
debug = 1


[profile.dev.package."*"]
debug = false
opt-level = 1         

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 16
strip = true
