[workspace]
members = [ ".", "common/assetscrawler", "common/texturedisplay" ]
exclude = [ "tools/*", "test/*" ]


[workspace.dependencies]
anyhow = "1.0.102"
image = "0.25.10"
serde = "1.0.228"
csv = "1.4.0"
toml = "1.1.2"
rand = "0.10.1"
tracing = "0.1.44"
tracing-appender = "0.2.5"


[workspace.dependencies.tracing-subscriber]
version = "0.3.23"
features = [ "env-filter", "fmt" ]


[workspace.dependencies.serde_json]
version = "1.0.150"
features = [ "preserve_order" ]


[workspace.package]
version = "0.1.1"
edition = "2024"
license = "MIT"
authors = [ "dlycn" ]


[package]
name = "toolkitengine"


[package.version]
workspace = true


[package.edition]
workspace = true


[package.authors]
workspace = true


[package.license]
workspace = true


[dependencies]
bevy_basisu_loader = "0.6.0"
bevy-inspector-egui = "0.37.0"
bevy_egui = "0.40.1"


[dependencies.tracing]
workspace = true


[dependencies.tracing-subscriber]
workspace = true


[dependencies.tracing-appender]
workspace = true


[dependencies.anyhow]
workspace = true


[dependencies.image]
workspace = true


[dependencies.serde]
workspace = true


[dependencies.toml]
workspace = true


[dependencies.serde_json]
workspace = true


[dependencies.csv]
workspace = true


[dependencies.rand]
workspace = true


[dependencies.bevy]
version = "0.19.0"
features = [ "default", "ktx2", "dds" ]


[dependencies.clap]
version = "4.6.1"
features = [ "derive", "color" ]


[profile.dev]
debug = 1


[profile.dev.package."*"]
debug = false
opt-level = 1


[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 16
strip = true
